use_frameworks!

platform :ios, '13.0'

target 'testlibcocoa_Example' do
  pod 'testlibcocoa', :path => '../'
  pod 'Alamofire', '~> 4.9'

  target 'testlibcocoa_Tests' do
    inherit! :search_paths

    
  end
end
